### ISSUE TITLE
Errors after import

### ISSUE THREAD

**Issue by EvanDaley** [YondernautsGames/NeoFPS_EmeraldAI#2]
I got 4 errors after cloning this into a fresh project NeoFPS / Emerald project

Assets\NeoFPS_EmeraldAI\Scripts\EmeraldAIPlayerDamage.cs(23,18): error CS0101: The namespace 'EmeraldAI' already contains a definition for 'EmeraldAIPlayerDamage'

Assets\NeoFPS_EmeraldAI\Scripts\NeoFpsEmeraldAI_InitializerOverride.cs(28,30): error CS0506: 'NeoFpsEmeraldAI_InitializerOverride.DisableRagdoll()': cannot override inherited member 'EmeraldAIInitializer.DisableRagdoll()' because it is not marked virtual, abstract, or override

Assets\NeoFPS_EmeraldAI\Scripts\NeoFpsEmeraldAI_InitializerOverride.cs(44,30): error CS0506: 'NeoFpsEmeraldAI_InitializerOverride.EnableRagdoll()': cannot override inherited member 'EmeraldAIInitializer.EnableRagdoll()' because it is not marked virtual, abstract, or override

Assets\NeoFPS_EmeraldAI\Scripts\EmeraldAIPlayerDamage.cs(89,21): error CS0111: Type 'EmeraldAIPlayerDamage' already defines a member called 'SendPlayerDamage' with the same parameter types

**Comment by EvanDaley** [comment]
I'm using emerald 3 and the emerald 3 branch of this repo

**Comment by EvanDaley** [comment]
I found this in the source code - might be worthwhile to mention this in the readme so people don't get stuck

        // This class is a workaround to enable location based damage (eg headshots) to Emerald AI characters.
        // Using this class requires modifying the Emerald AI source code, so it is sensitive to changes in the API.
        // To use it you will need to perform the following steps:
        // 1 - In the EmeraldAIInitializer.cs script, make the EmeraldComponent protected
        // 2 - Make the EnableRagdoll() and DisableRagdoll() methods virtual
		// 3 - Uncomment the code above
        // 4 - Replace the Emerald AI Initializer component on your AI with this class
        // 5 - Add any ragdoll colliders to the m_RagdollColliders array in the inspector
        // 6 - Move the root object of the Emerald AI character (only the root object) to the CharacterControllers layer
        // 7 - Remove the NeoFpsEmeraldAI_DamageHandler component from the root object of the character
        // 8 - Add damage handlers to the character's skeleton (eg, limbs, head and torso)
        //   a - Create a new child object of the relevant bone and set it to the CharacterPhysics layer
        //   b - Add a collider that is roughly the shape required
        //   c - Add a NeoFpsEmeraldAI_DamageHandler component and set it up with the desired values (note that the Emerald demo characters have 10 health, so a multiplier of less than 1 is used in most cases)

**Comment by YondernautsGames** [comment]
Hi there. The first and last errors you were getting will be fixed by deleting emerald's version of the EmeraldAIPlayerDamage.cs script (or commenting out its contents). Emerald AI 3 wasn't well architected from an extensibility point of view. Emerald AI 2024 is much better in that respect, properly leveraging interfaces and virtual methods.

The script you saw with the comments in is legacy and not required if you use the latest version of Emerald AI 3. They added a better way of handling the limb colliders that doesn't require an overridden initialiser to keep them active. I'll try and make it clearer in the readme and comments that this is the case.

**Comment by YondernautsGames** [comment]
It seems the `NeoFpsEmeraldAI_InitializerOverride.cs` script had accidentally been committed with the comments disabling the method overrides removed. I've re-added those, moved the instructions up towards the top, and re-emphasised that this script is legacy
