### ISSUE TITLE
Damage and Location Based Damage Handler

### ISSUE THREAD

**Issue by ericborn** [YondernautsGames/NeoFPS_EmeraldAI#3]
There are a couple bugs relating to the AddDamage method in both the NeoFpsEmeraldAI_LocationBasedDamageHandler and NeoFpsEmeraldAI_DamageHandler scripts.

Line 104 in the damage handler and line 94 in the location script reads:
bool isDead = m_EmeraldAISystem.HealthComponent.Health > 0;

This would make the bool return True if the AI has greater than 0 health, which seems counterintuitive since it is named isDead. 

As a result the if check where !isDead on line 135 and 116 respectively reads as not isDead, which would return true, but then you're evaluating if the m_EmeraldAISystem.HealthComponent.Health is > 0 which would also be true, but the comment and result of that function is reporting the AI being killed, which would trigger every time an enemy is damaged except if their health was negative.

Suggested fixes
bool isDead = m_EmeraldAISystem.HealthComponent.Health <= 0;
if (!isDead && m_EmeraldAISystem.HealthComponent.Health <= 0 && source.controller.isPlayer)
{
     OnPlayerKilledAI();
}

Message me as S3ND 1T on the Discord server if you have questions or something doesn't make sense.

**Comment by YondernautsGames** [comment]
Fixed
